//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Rules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment_Rules()
        {
            this.MAP_AssessmentRule_AssessmentItem = new HashSet<MAP_AssessmentRule_AssessmentItem>();
            this.MAP_AssessmentRule_SettlementMethod = new HashSet<MAP_AssessmentRule_SettlementMethod>();
        }
    
        public int AssessmentRuleID { get; set; }
        public string AssessmentRuleCode { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string AssessmentRuleName { get; set; }
        public Nullable<int> RuleRunID { get; set; }
        public Nullable<int> PaymentFrequencyID { get; set; }
        public Nullable<decimal> AssessmentAmount { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<int> PaymentOptionID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TaxMonth { get; set; }
    
        public virtual MST_RuleRun MST_RuleRun { get; set; }
        public virtual Payment_Frequency Payment_Frequency { get; set; }
        public virtual Payment_Options Payment_Options { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_AssessmentRule_AssessmentItem> MAP_AssessmentRule_AssessmentItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_AssessmentRule_SettlementMethod> MAP_AssessmentRule_SettlementMethod { get; set; }
    }
}
