//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment_Items()
        {
            this.MAP_Assessment_AssessmentItem = new HashSet<MAP_Assessment_AssessmentItem>();
            this.MAP_AssessmentRule_AssessmentItem = new HashSet<MAP_AssessmentRule_AssessmentItem>();
        }
    
        public int AssessmentItemID { get; set; }
        public string AssessmentItemReferenceNo { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> AssessmentGroupID { get; set; }
        public Nullable<int> AssessmentSubGroupID { get; set; }
        public Nullable<int> RevenueStreamID { get; set; }
        public Nullable<int> RevenueSubStreamID { get; set; }
        public Nullable<int> AssessmentItemCategoryID { get; set; }
        public Nullable<int> AssessmentItemSubCategoryID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string AssessmentItemName { get; set; }
        public Nullable<int> ComputationID { get; set; }
        public Nullable<decimal> TaxBaseAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Assessment_Group Assessment_Group { get; set; }
        public virtual Assessment_Item_Category Assessment_Item_Category { get; set; }
        public virtual Assessment_Item_SubCategory Assessment_Item_SubCategory { get; set; }
        public virtual Assessment_SubGroup Assessment_SubGroup { get; set; }
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual MST_Computation MST_Computation { get; set; }
        public virtual Revenue_Stream Revenue_Stream { get; set; }
        public virtual Revenue_SubStream Revenue_SubStream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Assessment_AssessmentItem> MAP_Assessment_AssessmentItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_AssessmentRule_AssessmentItem> MAP_AssessmentRule_AssessmentItem { get; set; }
    }
}
