//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.MAP_Assessment_AssessmentRule = new HashSet<MAP_Assessment_AssessmentRule>();
            this.Settlements = new HashSet<Settlement>();
        }
    
        public long AssessmentID { get; set; }
        public string AssessmentRefNo { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public Nullable<int> TaxPayerID { get; set; }
        public Nullable<decimal> AssessmentAmount { get; set; }
        public Nullable<System.DateTime> SettlementDueDate { get; set; }
        public Nullable<int> SettlementStatusID { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string AssessmentNotes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BillPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Assessment_AssessmentRule> MAP_Assessment_AssessmentRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settlement> Settlements { get; set; }
    }
}
