//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public long ALID { get; set; }
        public Nullable<int> ASLID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string Comment { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual AL_Screen AL_Screen { get; set; }
    }
}
