//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.MAP_Building_BuildingUnit = new HashSet<MAP_Building_BuildingUnit>();
            this.MAP_Building_Land = new HashSet<MAP_Building_Land>();
            this.MAP_Business_Building = new HashSet<MAP_Business_Building>();
            this.MAP_Company_AddressInformation = new HashSet<MAP_Company_AddressInformation>();
            this.MAP_Government_AddressInformation = new HashSet<MAP_Government_AddressInformation>();
            this.MAP_Individual_AddressInformation = new HashSet<MAP_Individual_AddressInformation>();
            this.MAP_Special_AddressInformation = new HashSet<MAP_Special_AddressInformation>();
            this.Tax_Offices = new HashSet<Tax_Offices>();
        }
    
        public int BuildingID { get; set; }
        public string BuildingRIN { get; set; }
        public string BuildingTagNumber { get; set; }
        public string BuildingName { get; set; }
        public string BuildingNumber { get; set; }
        public string StreetName { get; set; }
        public string OffStreetName { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> LGAID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> BuildingTypeID { get; set; }
        public Nullable<int> BuildingCompletionID { get; set; }
        public Nullable<int> BuildingPurposeID { get; set; }
        public Nullable<int> BuildingOwnershipID { get; set; }
        public Nullable<int> NoOfUnits { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<decimal> BuildingSize_Length { get; set; }
        public Nullable<decimal> BuildingSize_Width { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<long> DSRefID { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual Building_Completion Building_Completion { get; set; }
        public virtual Building_Ownership Building_Ownership { get; set; }
        public virtual Building_Purpose Building_Purpose { get; set; }
        public virtual Building_Types Building_Types { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual Town Town { get; set; }
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Building_BuildingUnit> MAP_Building_BuildingUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Building_Land> MAP_Building_Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Business_Building> MAP_Business_Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Company_AddressInformation> MAP_Company_AddressInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Government_AddressInformation> MAP_Government_AddressInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Individual_AddressInformation> MAP_Individual_AddressInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Special_AddressInformation> MAP_Special_AddressInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Offices> Tax_Offices { get; set; }
    }
}
