//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.MAP_Business_Building = new HashSet<MAP_Business_Building>();
        }
    
        public int BusinessID { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public string BusinessRIN { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> LGAID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> BusinessCategoryID { get; set; }
        public Nullable<int> BusinessSectorID { get; set; }
        public Nullable<int> BusinessSubSectorID { get; set; }
        public Nullable<int> BusinessStructureID { get; set; }
        public Nullable<int> BusinessOperationID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public string ContactName { get; set; }
        public string BusinessNumber { get; set; }
        public string BusinessAddress { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<long> DSRefID { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> TaxOfficeID { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual Business_Category Business_Category { get; set; }
        public virtual Business_Operation Business_Operation { get; set; }
        public virtual Business_Sector Business_Sector { get; set; }
        public virtual Business_Structure Business_Structure { get; set; }
        public virtual Business_SubSector Business_SubSector { get; set; }
        public virtual Business_Types Business_Types { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Business_Building> MAP_Business_Building { get; set; }
    }
}
