//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Certificate_Types()
        {
            this.MAP_CertificateType_Field = new HashSet<MAP_CertificateType_Field>();
            this.Certificates = new HashSet<Certificate>();
        }
    
        public int CertificateTypeID { get; set; }
        public string CertificateTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public string CNPrefix { get; set; }
        public Nullable<int> CNSerialNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> SEDE_PDFTemplateID { get; set; }
        public string CertificateTemplatePath { get; set; }
        public Nullable<int> SignMode { get; set; }
        public Nullable<int> Approver1 { get; set; }
        public Nullable<int> Approver2 { get; set; }
        public Nullable<int> ProcessingTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_CertificateType_Field> MAP_CertificateType_Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificate> Certificates { get; set; }
    }
}
