//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class combined_A_AR_AI3
    {
        public Nullable<long> S_N { get; set; }
        public long assessmentId { get; set; }
        public Nullable<int> SettlementStatusID { get; set; }
        public long AARID { get; set; }
        public Nullable<int> assessmentruleid { get; set; }
        public Nullable<int> AssessmentItemID { get; set; }
        public long AAIID { get; set; }
        public Nullable<decimal> TaxBaseAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
