//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DA_And_PAYE_TCC_Details
    {
        public int TccRequestId { get; set; }
        public byte RevenueStreamTypeId { get; set; }
        public string BusinessId { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public string BusinessName { get; set; }
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> LgaId { get; set; }
        public string LgaName { get; set; }
        public Nullable<decimal> IncomeAmount { get; set; }
        public Nullable<decimal> AssessedAmount { get; set; }
        public string TaxPaid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string ReceiptDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> chargeableIncome { get; set; }
        public Nullable<decimal> AnnualTax { get; set; }
        public Nullable<decimal> AnnualTaxII { get; set; }
    }
}
