//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ImportLog
    {
        public long ImportLogID { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public string ImportFilePath { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> TotalRecord { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
