//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_PD_MVA_Pending
    {
        public long PDMVPID { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<int> TaxMonth { get; set; }
        public string PaymentRefNumber { get; set; }
        public string PaymentDateTime { get; set; }
        public string AssessmentReference { get; set; }
        public string ReceiptNo { get; set; }
        public string RIN { get; set; }
        public string CustomerName { get; set; }
        public string RevenueItem { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string DepositSlip { get; set; }
        public string ChequeValueDate { get; set; }
        public string Bank { get; set; }
        public string AdditionalInfo { get; set; }
        public string BankBranch { get; set; }
        public string TaxPayerType { get; set; }
        public string PaymentCode { get; set; }
        public string RetrievalRefNumber { get; set; }
        public string AuthID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
