//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DAInput
{
    public int DAInputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Business_RIN { get; set; }
    public string Business_TIN { get; set; }
    public string Salaries { get; set; }
    public string Wages { get; set; }
    public string Trade { get; set; }
    public string Share_of_Partnership_Profit { get; set; }
    public string Commissions_Recieved { get; set; }
    public string Bonuses { get; set; }
    public string Gratuities { get; set; }
    public string Annuity { get; set; }
    public string Rent { get; set; }
    public string Interest_on_Discount { get; set; }
    public string Other_Incomes_Not_Included { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF__Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string PAYE_Income { get; set; }
    public string Assessment_Year { get; set; }
    public string Start_Month { get; set; }
    public string tax_office { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
}

public partial class DAOutput
{
    public int DAOutputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Business_RIN { get; set; }
    public string Business_TIN { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF_Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Income { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string Share_of_Assessment { get; set; }
    public string Assessment_Year { get; set; }
    public string tax_office { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
}

public partial class PAYEInput
{
    public int PAYEinputID { get; set; }
    public Nullable<System.DateTime> TransactionDate { get; set; }
    public string Employer_RIN { get; set; }
    public string Employee_RIN { get; set; }
    public string Tax_Office { get; set; }
    public Nullable<int> Assessment_Year { get; set; }
    public Nullable<int> Start_Month { get; set; }
    public Nullable<int> End_Month { get; set; }
    public Nullable<decimal> Annual_Basic { get; set; }
    public Nullable<decimal> Annual_Rent { get; set; }
    public Nullable<decimal> Annual_Transport { get; set; }
    public Nullable<decimal> Annual_Utility { get; set; }
    public Nullable<decimal> Annual_Meal { get; set; }
    public Nullable<decimal> Other_Allowances_Annual { get; set; }
    public Nullable<decimal> Leave_Transport_Grant_Annual { get; set; }
    public Nullable<decimal> pension_contribution_declared { get; set; }
    public Nullable<decimal> nhf_contribution_declared { get; set; }
    public Nullable<decimal> nhis_contribution_declared { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
}

public partial class PAYEOutput
{
    public int PAYEOutputID { get; set; }
    public Nullable<System.DateTime> Transaction_Date { get; set; }
    public string Employer_Rin { get; set; }
    public string Employee_Rin { get; set; }
    public Nullable<int> AssessmentYear { get; set; }
    public Nullable<int> Assessment_Month { get; set; }
    public Nullable<decimal> Monthly_Gross { get; set; }
    public Nullable<decimal> Monthly_CRA { get; set; }
    public Nullable<decimal> Monthly_ValidatedPension { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHF { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHIS { get; set; }
    public Nullable<decimal> Monthly_TaxFreePay { get; set; }
    public Nullable<decimal> Monthly_ChargeableIncome { get; set; }
    public Nullable<decimal> Monthly_Tax { get; set; }
    public string Tax_Office { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
}

public partial class vw_DAInputList
{
    public int DAInputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Business_RIN { get; set; }
    public string Business_TIN { get; set; }
    public string Salaries { get; set; }
    public string Wages { get; set; }
    public string Trade { get; set; }
    public string Share_of_Partnership_Profit { get; set; }
    public string Commissions_Recieved { get; set; }
    public string Bonuses { get; set; }
    public string Gratuities { get; set; }
    public string Annuity { get; set; }
    public string Rent { get; set; }
    public string Interest_on_Discount { get; set; }
    public string Other_Incomes_Not_Included { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF__Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string PAYE_Income { get; set; }
    public string Assessment_Year { get; set; }
    public string Start_Month { get; set; }
    public string tax_office { get; set; }
}

public partial class vw_DAOutputList
{
    public int DAOutputID { get; set; }
    public string transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Business_RIN { get; set; }
    public string Business_TIN { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF_Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Income { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string Share_of_Assessment { get; set; }
    public string Assessment_Year { get; set; }
    public string tax_office { get; set; }
}

public partial class vw_PAYEInputList
{
    public int PAYEinputID { get; set; }
    public Nullable<System.DateTime> TransactionDate { get; set; }
    public string Employer_RIN { get; set; }
    public string Employee_RIN { get; set; }
    public string Tax_Office { get; set; }
    public Nullable<int> Assessment_Year { get; set; }
    public Nullable<int> Start_Month { get; set; }
    public Nullable<int> End_Month { get; set; }
    public Nullable<decimal> Annual_Basic { get; set; }
    public Nullable<decimal> Annual_Transport { get; set; }
    public Nullable<decimal> Annual_Utility { get; set; }
    public Nullable<decimal> Annual_Meal { get; set; }
    public Nullable<decimal> Other_Allowances_Annual { get; set; }
    public Nullable<decimal> Leave_Transport_Grant_Annual { get; set; }
    public Nullable<decimal> pension_contribution_declared { get; set; }
    public Nullable<decimal> nhf_contribution_declared { get; set; }
    public Nullable<decimal> nhis_contribution_declared { get; set; }
    public Nullable<decimal> Annual_Rent { get; set; }
}

public partial class vw_PAYEOutput
{
    public int PAYEOutputID { get; set; }
    public Nullable<System.DateTime> Transaction_Date { get; set; }
    public string Employer_Rin { get; set; }
    public string Employee_Rin { get; set; }
    public Nullable<int> AssessmentYear { get; set; }
    public Nullable<int> Assessment_Month { get; set; }
    public Nullable<decimal> Monthly_Gross { get; set; }
    public Nullable<decimal> Monthly_CRA { get; set; }
    public Nullable<decimal> Monthly_ValidatedPension { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHF { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHIS { get; set; }
    public Nullable<decimal> Monthly_TaxFreePay { get; set; }
    public Nullable<decimal> Monthly_ChargeableIncome { get; set; }
    public Nullable<decimal> Monthly_Tax { get; set; }
    public string Tax_Office { get; set; }
}

public partial class usp_GetDAInputList_Result
{
    public Nullable<int> DAInputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Business_RIN { get; set; }
    public string Business_TIN { get; set; }
    public string Salaries { get; set; }
    public string Wages { get; set; }
    public string Trade { get; set; }
    public string Share_of_Partnership_Profit { get; set; }
    public string Commissions_Recieved { get; set; }
    public string Bonuses { get; set; }
    public string Gratuities { get; set; }
    public string Annuity { get; set; }
    public string Rent { get; set; }
    public string Interest_on_Discount { get; set; }
    public string Other_Incomes_Not_Included { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF__Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string PAYE_Income { get; set; }
    public string Assessment_Year { get; set; }
    public string Start_Month { get; set; }
    public string tax_office { get; set; }
}

public partial class usp_GetDAOutputList_Result
{
    public Nullable<int> DAOutputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string Taxpayer_RIN { get; set; }
    public string Taxpayer_TIN { get; set; }
    public string Total_Income { get; set; }
    public string Pension_Contribution_Declared { get; set; }
    public string NHF_Declared { get; set; }
    public string NHIS_Declared { get; set; }
    public string Life_Assurance { get; set; }
    public string PAYE_Income { get; set; }
    public string PAYE_Pension { get; set; }
    public string PAYE_NHF { get; set; }
    public string PAYE_NHIS { get; set; }
    public string Employee_PAYE_Contribution { get; set; }
    public string Share_of_Assessment { get; set; }
    public string Assessment_Year { get; set; }
    public string Start_Month { get; set; }
    public string tax_office { get; set; }
}

public partial class usp_GetPAYEInputList_Result
{
    public Nullable<int> PAYEInputID { get; set; }
    public Nullable<System.DateTime> transaction_date { get; set; }
    public string employer_rin { get; set; }
    public string employee_rin { get; set; }
    public Nullable<int> assessment_year { get; set; }
    public Nullable<int> start_month { get; set; }
    public Nullable<int> end_month { get; set; }
    public Nullable<decimal> annual_basic { get; set; }
    public Nullable<decimal> annual_rent { get; set; }
    public Nullable<decimal> annual_transport { get; set; }
    public Nullable<decimal> annual_utility { get; set; }
    public Nullable<decimal> annual_meal { get; set; }
    public Nullable<decimal> other_allowances_annual { get; set; }
    public Nullable<decimal> leave_transport_grant_annual { get; set; }
    public Nullable<decimal> pension_contribution_declared { get; set; }
    public Nullable<decimal> nhf_contribution_declared { get; set; }
    public Nullable<decimal> nhis_contribution_declared { get; set; }
    public string Tax_Office { get; set; }
}

public partial class usp_GETPAYEOutput_Result
{
    public Nullable<int> PayeOutputID { get; set; }
    public Nullable<System.DateTime> Transaction_Date { get; set; }
    public string Employer_Rin { get; set; }
    public string Employee_Rin { get; set; }
    public Nullable<int> AssessmentYear { get; set; }
    public Nullable<int> Assessment_Month { get; set; }
    public Nullable<decimal> Monthly_Gross { get; set; }
    public Nullable<decimal> Monthly_CRA { get; set; }
    public Nullable<decimal> Monthly_ValidatedPension { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHF { get; set; }
    public Nullable<decimal> Monthly_ValidatedNHIS { get; set; }
    public Nullable<decimal> Monthly_TaxFreePay { get; set; }
    public Nullable<decimal> Monthly_ChargeableIncome { get; set; }
    public Nullable<decimal> Monthly_Tax { get; set; }
    public string Tax_Office { get; set; }
}

public partial class usp_RPT_PAYEOutputAggregationList_Result
{
    public string EmployeeName { get; set; }
    public string EmployeeRIN { get; set; }
    public decimal AmountContributed { get; set; }
}

public partial class usp_RPT_PAYEOutputAggregationSummary_Result
{
    public string EmployerName { get; set; }
    public string EmployerRIN { get; set; }
    public int EmployeeCount { get; set; }
    public decimal AmountCollected { get; set; }
}
