//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Individual()
        {
            this.MAP_Individual_AddressInformation = new HashSet<MAP_Individual_AddressInformation>();
        }
    
        public int IndividualID { get; set; }
        public string IndividualRIN { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string TIN { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string EmailAddress1 { get; set; }
        public string EmailAddress2 { get; set; }
        public string BiometricDetails { get; set; }
        public Nullable<int> TaxOfficeID { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public Nullable<int> EconomicActivitiesID { get; set; }
        public Nullable<int> NotificationMethodID { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Password { get; set; }
        public Nullable<int> RegisterationStatusID { get; set; }
        public Nullable<System.DateTime> RegisterationDate { get; set; }
        public Nullable<int> VerificationOTP { get; set; }
        public Nullable<int> TaxOfficerID { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<long> DSRefID { get; set; }
        public string NIN { get; set; }
    
        public virtual Economic_Activities Economic_Activities { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Notification_Method Notification_Method { get; set; }
        public virtual TaxPayer_Types TaxPayer_Types { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Individual_AddressInformation> MAP_Individual_AddressInformation { get; set; }
        public virtual MST_RegisterationStatus MST_RegisterationStatus { get; set; }
        public virtual Tax_Offices Tax_Offices { get; set; }
    }
}
