//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JTB_Individual
    {
        public long JTBIndividualID { get; set; }
        public string tin { get; set; }
        public string bvn { get; set; }
        public string nin { get; set; }
        public string Title { get; set; }
        public string SBIRt_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string GenderName { get; set; }
        public string StateOfOrigin { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string MaritalStatus { get; set; }
        public string Occupation { get; set; }
        public string nationality_name { get; set; }
        public string phone_no_1 { get; set; }
        public string phone_no_2 { get; set; }
        public string taxpayer_photo { get; set; }
        public string email_address { get; set; }
        public Nullable<System.DateTime> date_of_registration { get; set; }
        public string house_number { get; set; }
        public string street_name { get; set; }
        public string city { get; set; }
        public string LGAName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string TaxAuthorityCode { get; set; }
        public string TaxAuthorityName { get; set; }
        public string TaxpayerStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
