//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JTB_NonIndividual
    {
        public long JTBNonIndividualID { get; set; }
        public string tin { get; set; }
        public string registered_name { get; set; }
        public string main_trade_name { get; set; }
        public string org_name { get; set; }
        public string registration_number { get; set; }
        public string phone_no_1 { get; set; }
        public string phone_no_2 { get; set; }
        public string email_address { get; set; }
        public string line_of_business_code { get; set; }
        public string lob_name { get; set; }
        public Nullable<System.DateTime> date_of_registration { get; set; }
        public Nullable<System.DateTime> commencement_date { get; set; }
        public Nullable<System.DateTime> date_of_incorporation { get; set; }
        public string house_number { get; set; }
        public string street_name { get; set; }
        public string city { get; set; }
        public string LGAName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string FinYrBegin { get; set; }
        public string FinYrEnd { get; set; }
        public string director_name { get; set; }
        public string director_phone { get; set; }
        public string director_email { get; set; }
        public string TaxAuthorityCode { get; set; }
        public string TaxAuthorityName { get; set; }
        public string TaxpayerStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
