//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Land()
        {
            this.MAP_Building_Land = new HashSet<MAP_Building_Land>();
        }
    
        public int LandID { get; set; }
        public string LandRIN { get; set; }
        public string PlotNumber { get; set; }
        public string StreetName { get; set; }
        public string LandOccupier { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> LGAID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<decimal> LandSize_Length { get; set; }
        public Nullable<decimal> LandSize_Width { get; set; }
        public string C_OF_O_Ref { get; set; }
        public Nullable<int> LandDevelopmentID { get; set; }
        public Nullable<int> LandPurposeID { get; set; }
        public Nullable<int> LandFunctionID { get; set; }
        public Nullable<int> LandOwnershipID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<decimal> ValueOfLand { get; set; }
        public Nullable<int> LandStreetConditionID { get; set; }
        public string Neighborhood { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<long> DSRefID { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual Land_Development Land_Development { get; set; }
        public virtual Land_Function Land_Function { get; set; }
        public virtual Land_Ownership Land_Ownership { get; set; }
        public virtual Land_Purpose Land_Purpose { get; set; }
        public virtual Land_StreetCondition Land_StreetCondition { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual Town Town { get; set; }
        public virtual Ward Ward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Building_Land> MAP_Building_Land { get; set; }
    }
}
