//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ServiceBill_MDAService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_ServiceBill_MDAService()
        {
            this.MAP_ServiceBill_MDAServiceItem = new HashSet<MAP_ServiceBill_MDAServiceItem>();
        }
    
        public long SBSID { get; set; }
        public Nullable<long> ServiceBillID { get; set; }
        public Nullable<int> MDAServiceID { get; set; }
        public Nullable<int> ServiceBillYear { get; set; }
        public Nullable<decimal> ServiceAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MDA_Services MDA_Services { get; set; }
        public virtual ServiceBill ServiceBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_ServiceBill_MDAServiceItem> MAP_ServiceBill_MDAServiceItem { get; set; }
    }
}
