//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ServiceBill_MDAServiceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_ServiceBill_MDAServiceItem()
        {
            this.MAP_Settlement_SettlementItem = new HashSet<MAP_Settlement_SettlementItem>();
            this.MAP_ServiceBill_Adjustment = new HashSet<MAP_ServiceBill_Adjustment>();
            this.MAP_ServiceBill_LateCharge = new HashSet<MAP_ServiceBill_LateCharge>();
        }
    
        public long SBSIID { get; set; }
        public Nullable<long> SBSID { get; set; }
        public Nullable<int> MDAServiceItemID { get; set; }
        public Nullable<decimal> ServiceBaseAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> ServiceAmount { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MDA_Service_Items MDA_Service_Items { get; set; }
        public virtual MDA_Service_Items MDA_Service_Items1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Settlement_SettlementItem> MAP_Settlement_SettlementItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_ServiceBill_Adjustment> MAP_ServiceBill_Adjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_ServiceBill_LateCharge> MAP_ServiceBill_LateCharge { get; set; }
        public virtual MAP_ServiceBill_MDAService MAP_ServiceBill_MDAService { get; set; }
    }
}
