//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_MDAService_MDAServiceItem
    {
        public int MSMSIID { get; set; }
        public Nullable<int> MDAServiceID { get; set; }
        public Nullable<int> MDAServiceItemID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual MDA_Services MDA_Services { get; set; }
        public virtual MDA_Service_Items MDA_Service_Items { get; set; }
    }
}
