//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_Certificate_SignVisible
    {
        public long CSVID { get; set; }
        public Nullable<long> CertificateID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SignSourceID { get; set; }
        public string AdditionalSignatureLocation { get; set; }
        public Nullable<int> StageID { get; set; }
        public string DocumentWidth { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
