//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_CertificateType_Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_CertificateType_Field()
        {
            this.MAP_Certificate_CustomField = new HashSet<MAP_Certificate_CustomField>();
        }
    
        public int CTFID { get; set; }
        public Nullable<int> CertificateTypeID { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldTypeID { get; set; }
        public string FieldComboValue { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FieldSlug { get; set; }
    
        public virtual Certificate_Types Certificate_Types { get; set; }
        public virtual MST_FieldType MST_FieldType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Certificate_CustomField> MAP_Certificate_CustomField { get; set; }
    }
}
