//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_Certificate_CustomField
    {
        public int CCFID { get; set; }
        public Nullable<int> CTFID { get; set; }
        public Nullable<long> CertificateID { get; set; }
        public string FieldValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual MAP_CertificateType_Field MAP_CertificateType_Field { get; set; }
    }
}
