//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_PaymentAccount_Operation
    {
        public int POAID { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> OperationTypeID { get; set; }
        public Nullable<int> From_TaxPayerTypeID { get; set; }
        public Nullable<int> From_TaxPayerID { get; set; }
        public Nullable<int> From_SettlementMethodID { get; set; }
        public Nullable<int> To_TaxPayerTypeID { get; set; }
        public Nullable<int> To_TaxPayerID { get; set; }
        public Nullable<int> To_BillTypeID { get; set; }
        public Nullable<int> To_BillID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> ModifiedDate { get; set; }
        public int POAAccountId { get; set; }
        public string TransactionRefNo { get; set; }
    }
}
