//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_TaxPayer_Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_TaxPayer_Asset()
        {
            this.MAP_TaxPayer_Asset_Profile = new HashSet<MAP_TaxPayer_Asset_Profile>();
        }
    
        public long TPAID { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public Nullable<int> TaxPayerID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> TaxPayerRoleID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> BuildingUnitID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_TaxPayer_Asset_Profile> MAP_TaxPayer_Asset_Profile { get; set; }
        public virtual TaxPayer_Roles TaxPayer_Roles { get; set; }
        public virtual TaxPayer_Types TaxPayer_Types { get; set; }
    }
}
