//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_ServiceBill_Adjustment
    {
        public long SADID { get; set; }
        public Nullable<long> SBSIID { get; set; }
        public Nullable<System.DateTime> AdjustmentDate { get; set; }
        public Nullable<int> AdjustmentTypeID { get; set; }
        public string AdjustmentLine { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MAP_ServiceBill_MDAServiceItem MAP_ServiceBill_MDAServiceItem { get; set; }
    }
}
