//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map_PoA_Transfer_Operation
    {
        public int POATID { get; set; }
        public string POATRefNo { get; set; }
        public string From_PoaTransactionRefNo { get; set; }
        public Nullable<int> From_Taxpayer_POAID { get; set; }
        public Nullable<int> From_TaxpayerID { get; set; }
        public Nullable<int> From_TaxpayerTypeID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> To_TaxpayerID { get; set; }
        public Nullable<int> To_TaxpayerTypeID { get; set; }
        public Nullable<int> To_Taxpayer_POAID { get; set; }
        public string To_TransactionRefNo { get; set; }
        public Nullable<int> Settlement_MethodID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
