//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_TCCRequest_Generate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_TCCRequest_Generate()
        {
            this.MAP_TCCRequest_Generate_Field = new HashSet<MAP_TCCRequest_Generate_Field>();
        }
    
        public long RGID { get; set; }
        public Nullable<long> RequestID { get; set; }
        public string Notes { get; set; }
        public string Reason { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsExpirable { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_TCCRequest_Generate_Field> MAP_TCCRequest_Generate_Field { get; set; }
        public virtual TCC_Request TCC_Request { get; set; }
    }
}
