//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_TCCRequest_IncomeStream
    {
        public long TRISID { get; set; }
        public Nullable<long> TCCRequestID { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public Nullable<int> TaxPayerRoleID { get; set; }
        public Nullable<decimal> TotalIncomeEarned { get; set; }
        public string Notes { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> BusinessTypeID { get; set; }
        public Nullable<int> LGAID { get; set; }
        public Nullable<int> BusinessOperationID { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessNumber { get; set; }
        public string ContactPersonName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
