//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAP_Assessment_AssessmentRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAP_Assessment_AssessmentRule()
        {
            this.MAP_Assessment_AssessmentItem = new HashSet<MAP_Assessment_AssessmentItem>();
        }
    
        public long AARID { get; set; }
        public Nullable<long> AssessmentID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public Nullable<int> AssessmentRuleID { get; set; }
        public Nullable<int> AssessmentYear { get; set; }
        public Nullable<decimal> AssessmentAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Assessment_AssessmentItem> MAP_Assessment_AssessmentItem { get; set; }
        public virtual Assessment Assessment { get; set; }
    }
}
