//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapAssessmentDisapprove_
    {
        public long Id { get; set; }
        public Nullable<long> AssessmentID { get; set; }
        public string Notes { get; set; }
        public Nullable<int> TaxOfficerId { get; set; }
        public string TaxOfficerDesignation { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
