//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDA_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDA_Services()
        {
            this.MAP_MDAService_MDAServiceItem = new HashSet<MAP_MDAService_MDAServiceItem>();
            this.MAP_MDAService_SettlementMethod = new HashSet<MAP_MDAService_SettlementMethod>();
            this.MAP_ServiceBill_MDAService = new HashSet<MAP_ServiceBill_MDAService>();
        }
    
        public int MDAServiceID { get; set; }
        public string MDAServiceCode { get; set; }
        public string MDAServiceName { get; set; }
        public Nullable<int> RuleRunID { get; set; }
        public Nullable<int> PaymentFrequencyID { get; set; }
        public Nullable<decimal> ServiceAmount { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<int> PaymentOptionID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_MDAService_MDAServiceItem> MAP_MDAService_MDAServiceItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_MDAService_SettlementMethod> MAP_MDAService_SettlementMethod { get; set; }
        public virtual MST_RuleRun MST_RuleRun { get; set; }
        public virtual Payment_Frequency Payment_Frequency { get; set; }
        public virtual Payment_Options Payment_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_ServiceBill_MDAService> MAP_ServiceBill_MDAService { get; set; }
    }
}
