//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_CertificateStage
    {
        public int CertificateStageID { get; set; }
        public string CertificateStageName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
    }
}
