//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Business
    {
        public long BusinessID { get; set; }
        public string BusinessName { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessSector { get; set; }
        public string BusinessSubSector { get; set; }
        public string BusinessType { get; set; }
        public string BusinessCategory { get; set; }
        public string AssetType { get; set; }
        public string BusinessStructure { get; set; }
        public string BusinessOperation { get; set; }
        public string Size { get; set; }
        public string LGA { get; set; }
        public string TIN { get; set; }
        public string TaxOffice { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> PAYE { get; set; }
        public Nullable<bool> DirectAssessment { get; set; }
        public Nullable<bool> PresumptiveTax { get; set; }
        public Nullable<bool> BusinessPremises { get; set; }
        public Nullable<bool> ConsumtpionTaxes { get; set; }
        public Nullable<bool> MDAServices { get; set; }
        public string Source { get; set; }
        public string BuildingTag { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> PhoneVerified { get; set; }
        public Nullable<bool> Claimed { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
