//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_Screen()
        {
            this.MAP_CentralMenu_Screen = new HashSet<MAP_CentralMenu_Screen>();
            this.MAP_User_Screen = new HashSet<MAP_User_Screen>();
        }
    
        public int ScreenID { get; set; }
        public string ScreenName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ViewName { get; set; }
        public string ScreenUrl { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_CentralMenu_Screen> MAP_CentralMenu_Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_User_Screen> MAP_User_Screen { get; set; }
    }
}
