//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_UserToken
    {
        public int TokenID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenIssuedDate { get; set; }
        public Nullable<System.DateTime> TokenExpiresDate { get; set; }
        public string IPAddresss { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual MST_Users MST_Users { get; set; }
    }
}
