//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_Users()
        {
            this.MAP_API_Users_Rights = new HashSet<MAP_API_Users_Rights>();
            this.MAP_User_Screen = new HashSet<MAP_User_Screen>();
            this.MST_UserToken = new HashSet<MST_UserToken>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ContactName { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<bool> IsTOManager { get; set; }
        public Nullable<int> TaxOfficeID { get; set; }
        public Nullable<int> TOManagerID { get; set; }
        public string SignaturePath { get; set; }
        public Nullable<bool> IsDirector { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_API_Users_Rights> MAP_API_Users_Rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_User_Screen> MAP_User_Screen { get; set; }
        public virtual MST_UserType MST_UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_UserToken> MST_UserToken { get; set; }
    }
}
