//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewERASTccHolder
    {
        public int Id { get; set; }
        public string RIN { get; set; }
        public Nullable<decimal> TotalIncomeEarned { get; set; }
        public Nullable<int> AssessmentYear { get; set; }
        public string Role { get; set; }
        public string BusinessName { get; set; }
        public string LGA { get; set; }
    }
}
