//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTCCDetailsHold
    {
        public int Id { get; set; }
        public Nullable<int> RowID { get; set; }
        public Nullable<long> TBKID { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<decimal> AssessableIncome { get; set; }
        public Nullable<decimal> TCCTaxPaid { get; set; }
        public Nullable<decimal> ERASTaxPaid { get; set; }
        public Nullable<decimal> ERASAssessed { get; set; }
        public string Tax_receipt { get; set; }
        public string IndividualRIN { get; set; }
        public Nullable<long> TCCRequestID { get; set; }
    }
}
