//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NINDetail
    {
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string TelephoneNo { get; set; }
        public string ResidenceAdressLine1 { get; set; }
        public string ResidenceTown { get; set; }
        public string ResidenceLga { get; set; }
        public string ResidenceState { get; set; }
        public string NIN { get; set; }
        public string Photo { get; set; }
        public string Profession { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string StateOfOrigin { get; set; }
        public string LgaOrigin { get; set; }
        public string BirthCountry { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string vNIN { get; set; }
    }
}
