//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationID { get; set; }
        public string NotificationRefNo { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public Nullable<int> NotificationMethodID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public string EventRefNo { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public Nullable<int> TaxPayerID { get; set; }
        public Nullable<int> NotificationModeID { get; set; }
        public Nullable<bool> NotificationStatus { get; set; }
        public string NotificationContent { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Notification_Method Notification_Method { get; set; }
        public virtual Notification_Mode Notification_Mode { get; set; }
        public virtual Notification_Type Notification_Type { get; set; }
    }
}
