//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayeTccHolder
    {
        public int Id { get; set; }
        public string IndividualRIN { get; set; }
        public Nullable<double> AnnualGross { get; set; }
        public Nullable<double> Cra { get; set; }
        public Nullable<double> ValidatedPension { get; set; }
        public Nullable<double> ValidatedNhf { get; set; }
        public Nullable<double> ValidatedNhis { get; set; }
        public Nullable<double> TaxFreePay { get; set; }
        public Nullable<double> ChargeableIncome { get; set; }
        public Nullable<double> AnnualTax { get; set; }
        public Nullable<double> AnnualTaxII { get; set; }
        public Nullable<double> MonthlyTax { get; set; }
        public Nullable<int> RowID { get; set; }
        public string AssessmentYear { get; set; }
        public string BusinessName { get; set; }
        public string ReceiptDetail { get; set; }
    }
}
