//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYEInput
    {
        public int PAYEinputID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Employer_RIN { get; set; }
        public string Employee_RIN { get; set; }
        public string Tax_Office { get; set; }
        public Nullable<int> Assessment_Year { get; set; }
        public Nullable<int> Start_Month { get; set; }
        public Nullable<int> End_Month { get; set; }
        public Nullable<decimal> Annual_Basic { get; set; }
        public Nullable<decimal> Annual_Rent { get; set; }
        public Nullable<decimal> Annual_Transport { get; set; }
        public Nullable<decimal> Annual_Utility { get; set; }
        public Nullable<decimal> Annual_Meal { get; set; }
        public Nullable<decimal> Other_Allowances_Annual { get; set; }
        public Nullable<decimal> Leave_Transport_Grant_Annual { get; set; }
        public Nullable<decimal> pension_contribution_declared { get; set; }
        public Nullable<decimal> nhf_contribution_declared { get; set; }
        public Nullable<decimal> nhis_contribution_declared { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
