//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Account
    {
        public long PaymentAccountID { get; set; }
        public string PaymentRefNo { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public Nullable<int> TaxPayerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> SettlementMethodID { get; set; }
        public Nullable<int> SettlementStatusID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Notes { get; set; }
        public string TransactionRefNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RevenueStreamID { get; set; }
        public Nullable<int> RevenueSubStreamID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<bool> isManualEntry { get; set; }
    
        public virtual Settlement_Method Settlement_Method { get; set; }
        public virtual Settlement_Status Settlement_Status { get; set; }
        public virtual TaxPayer_Types TaxPayer_Types { get; set; }
        public virtual Revenue_Stream Revenue_Stream { get; set; }
        public virtual Revenue_SubStream Revenue_SubStream { get; set; }
    }
}
