//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Settlement()
        {
            this.MAP_Settlement_SettlementItem = new HashSet<MAP_Settlement_SettlementItem>();
            this.MAP_TreasuryReceipt_Settlement = new HashSet<MAP_TreasuryReceipt_Settlement>();
        }
    
        public int SettlementID { get; set; }
        public string SettlementRefNo { get; set; }
        public Nullable<long> ServiceBillID { get; set; }
        public Nullable<long> AssessmentID { get; set; }
        public Nullable<decimal> SettlementAmount { get; set; }
        public Nullable<int> SettlementMethodID { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string SettlementNotes { get; set; }
        public string TransactionRefNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_Settlement_SettlementItem> MAP_Settlement_SettlementItem { get; set; }
        public virtual ServiceBill ServiceBill { get; set; }
        public virtual Settlement_Method Settlement_Method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_TreasuryReceipt_Settlement> MAP_TreasuryReceipt_Settlement { get; set; }
        public virtual Assessment Assessment { get; set; }
    }
}
