//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFTP_DataSubmissionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFTP_DataSubmissionType()
        {
            this.SFTP_MAP_DataSubmitter_DataSubmissionType = new HashSet<SFTP_MAP_DataSubmitter_DataSubmissionType>();
            this.SFTP_DataSubmission = new HashSet<SFTP_DataSubmission>();
        }
    
        public int DataSubmissionTypeID { get; set; }
        public string DataSubmissionTypeName { get; set; }
        public string TemplateFilePath { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFTP_MAP_DataSubmitter_DataSubmissionType> SFTP_MAP_DataSubmitter_DataSubmissionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFTP_DataSubmission> SFTP_DataSubmission { get; set; }
    }
}
