//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxPayer_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxPayer_Roles()
        {
            this.MAP_TaxPayer_Asset = new HashSet<MAP_TaxPayer_Asset>();
        }
    
        public int TaxPayerRoleID { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> TaxPayerTypeID { get; set; }
        public string TaxPayerRoleName { get; set; }
        public Nullable<bool> IsMultiLinkable { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAP_TaxPayer_Asset> MAP_TaxPayer_Asset { get; set; }
        public virtual TaxPayer_Types TaxPayer_Types { get; set; }
    }
}
