//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TccRefHolder
    {
        public int Id { get; set; }
        public string ReqId { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public string ReciptRef { get; set; }
        public Nullable<int> ReceiptDate { get; set; }
    }
}
