//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidateTcc
    {
        public int ID { get; set; }
        public string TaxpayerRIN { get; set; }
        public string TaxpayerTIN { get; set; }
        public string TCCCertificateNumber { get; set; }
        public Nullable<System.DateTime> DateofTCCissued { get; set; }
        public string TCCpdf { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> TccRequestId { get; set; }
        public string Fullname { get; set; }
        public string Taxyear { get; set; }
    }
}
