//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Vehicle_Insurance = new HashSet<Vehicle_Insurance>();
            this.Vehicle_Licenses = new HashSet<Vehicle_Licenses>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleRIN { get; set; }
        public string VehicleRegNumber { get; set; }
        public string VIN { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> VehicleSubTypeID { get; set; }
        public Nullable<int> LGAID { get; set; }
        public Nullable<int> VehiclePurposeID { get; set; }
        public Nullable<int> VehicleFunctionID { get; set; }
        public Nullable<int> VehicleOwnershipID { get; set; }
        public string VehicleDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DataSourceID { get; set; }
        public Nullable<long> DSRefID { get; set; }
    
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual LGA LGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Insurance> Vehicle_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Licenses> Vehicle_Licenses { get; set; }
        public virtual Vehicle_Function Vehicle_Function { get; set; }
        public virtual Vehicle_Ownership Vehicle_Ownership { get; set; }
        public virtual Vehicle_Purpose Vehicle_Purpose { get; set; }
        public virtual Vehicle_SubTypes Vehicle_SubTypes { get; set; }
        public virtual Vehicle_Types Vehicle_Types { get; set; }
    }
}
