//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BillForPoASettlement
    {
        public long BillID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public int BillTypeID { get; set; }
        public string BillTypeName { get; set; }
        public string BillRefNo { get; set; }
        public string TaxPayerName { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<int> SettlementStatusID { get; set; }
        public string SettlementStatusName { get; set; }
    }
}
