//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Profile_PAYE_PC_FBE_Asset
    {
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public string AssetRIN { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public string AssetTypeName { get; set; }
        public Nullable<int> TaxPayerCount { get; set; }
    }
}
