//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PaymentAccountOperation
    {
        public int POAID { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string Operation_TypesName { get; set; }
        public string FromTaxPayer { get; set; }
        public string FromName { get; set; }
        public string ToTaxPayer { get; set; }
        public string ToName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
