//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PAYEOutput
    {
        public int PAYEOutputID { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Employer_Rin { get; set; }
        public string Employee_Rin { get; set; }
        public Nullable<int> AssessmentYear { get; set; }
        public Nullable<int> Assessment_Month { get; set; }
        public Nullable<decimal> Monthly_Gross { get; set; }
        public Nullable<decimal> Monthly_CRA { get; set; }
        public Nullable<decimal> Monthly_ValidatedPension { get; set; }
        public Nullable<decimal> Monthly_ValidatedNHF { get; set; }
        public Nullable<decimal> Monthly_ValidatedNHIS { get; set; }
        public Nullable<decimal> Monthly_TaxFreePay { get; set; }
        public Nullable<decimal> Monthly_ChargeableIncome { get; set; }
        public Nullable<decimal> Monthly_Tax { get; set; }
        public string Tax_Office { get; set; }
    }
}
