//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Special
    {
        public int SpecialID { get; set; }
        public string SpecialRIN { get; set; }
        public string SpecialTaxPayerName { get; set; }
        public string TIN { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> TaxOfficeID { get; set; }
    }
}
