//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Vehicle
    {
        public int VehicleID { get; set; }
        public string VehicleRIN { get; set; }
        public string VehicleRegNumber { get; set; }
        public string VehicleSubTypeName { get; set; }
        public string VehiclePurposeName { get; set; }
    }
}
