//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneLGA
    {
        public int Id { get; set; }
        public string LgaName { get; set; }
        public string ZoneCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
